-- =============================================================================
-- duckstore: OLTP schema for the online store (Postgres)
--
-- This is a normalized (3NF) model, the kind you design for an application:
-- many small reads/writes, each touching a few rows, protected by constraints.
--
-- SQL Server notes:
--   * schema "store"                 ~ a schema like "dbo" or "Sales"
--   * bigint GENERATED ... IDENTITY  ~ bigint IDENTITY(1,1)
--   * text                           ~ nvarchar(max) (Postgres text has no length penalty)
--   * timestamptz                    ~ datetimeoffset (stored as UTC)
--   * numeric(12,2)                  ~ decimal(12,2)
--   * jsonb                          ~ nvarchar(max) + JSON functions, but binary and indexable
--
-- Primary keys, foreign keys and indexes are created AFTER the bulk load
-- (see 02_constraints.sql). Loading into bare tables and then building
-- indexes once is much faster, the same trick as in SQL Server bulk loads.
-- =============================================================================

DROP SCHEMA IF EXISTS store CASCADE;
CREATE SCHEMA store;
SET search_path = store;

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public; -- trigram index for product search

-- ---------------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------------

CREATE TABLE currencies (
    code        char(3) NOT NULL,
    name        text    NOT NULL,
    symbol      text    NOT NULL
);

CREATE TABLE countries (
    code          char(2)      NOT NULL,
    name          text         NOT NULL,
    region        text         NOT NULL,
    currency_code char(3)      NOT NULL,
    tax_rate      numeric(5,4) NOT NULL CHECK (tax_rate >= 0 AND tax_rate < 1)
);

-- One row per currency per BUSINESS day. Weekends have no row, so to convert an
-- order placed on a Sunday you need "the latest rate on or before that date".
-- In DuckDB that is an ASOF JOIN; in Postgres/SQL Server a LATERAL/APPLY TOP 1.
CREATE TABLE fx_rates (
    currency_code char(3)       NOT NULL,
    rate_date     date          NOT NULL,
    units_per_usd numeric(18,8) NOT NULL CHECK (units_per_usd > 0)
);

-- ---------------------------------------------------------------------------
-- People and places
-- ---------------------------------------------------------------------------

-- Self-referencing hierarchy (manager_id -> employees.id), like the classic
-- HumanResources.Employee in AdventureWorks. Query it with a recursive CTE.
CREATE TABLE employees (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    manager_id   bigint,
    first_name   text          NOT NULL,
    last_name    text          NOT NULL,
    email        text          NOT NULL,
    title        text          NOT NULL,
    department   text          NOT NULL CHECK (department IN ('Executive', 'Sales', 'Operations', 'Purchasing', 'Support', 'Finance')),
    region       text,
    warehouse_id bigint,
    hired_at     date          NOT NULL,
    salary_usd   numeric(12,2) NOT NULL
);

-- warehouses.manager_employee_id -> employees and employees.warehouse_id ->
-- warehouses form a circular reference. Legal, but you must load both tables
-- before enabling the constraints.
CREATE TABLE warehouses (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    code                text    NOT NULL,
    name                text    NOT NULL,
    country_code        char(2) NOT NULL,
    city                text    NOT NULL,
    manager_employee_id bigint
);

CREATE TABLE customers (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY,
    email                   text        NOT NULL,
    first_name              text        NOT NULL,
    last_name               text        NOT NULL,
    segment                 text        NOT NULL CHECK (segment IN ('consumer', 'business', 'vip')),
    country_code            char(2)     NOT NULL,
    referred_by_customer_id bigint,              -- self-reference: referral chains
    account_manager_id      bigint,              -- employees (Sales) for business/vip
    created_at              timestamptz NOT NULL
);

CREATE TABLE addresses (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id  bigint      NOT NULL,
    kind         text        NOT NULL CHECK (kind IN ('shipping', 'billing')),
    line1        text        NOT NULL,
    city         text        NOT NULL,
    postal_code  text        NOT NULL,
    country_code char(2)     NOT NULL,
    is_default   boolean     NOT NULL DEFAULT false
);

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------

-- Category tree of variable depth (2 to 4 levels).
CREATE TABLE categories (
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    parent_id bigint,
    name      text NOT NULL,
    slug      text NOT NULL
);

CREATE TABLE brands (
    id   bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL
);

CREATE TABLE suppliers (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    name         text     NOT NULL,
    country_code char(2)  NOT NULL,
    rating       smallint NOT NULL CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE products (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    sku         text          NOT NULL,
    name        text          NOT NULL,
    description text          NOT NULL,
    category_id bigint        NOT NULL,
    brand_id    bigint        NOT NULL,
    price_usd   numeric(12,2) NOT NULL CHECK (price_usd > 0), -- current price (= open row in product_prices)
    cost_usd    numeric(12,2) NOT NULL CHECK (cost_usd > 0),
    weight_kg   numeric(8,3)  NOT NULL,
    attributes  jsonb         NOT NULL DEFAULT '{}',          -- color, material, warranty...
    is_active   boolean       NOT NULL DEFAULT true,
    created_at  timestamptz   NOT NULL
);

-- Temporal table: the price history of each product. valid_to IS NULL means
-- "current price". The warehouse turns this into a Type 2 slowly changing dimension.
CREATE TABLE product_prices (
    product_id bigint        NOT NULL,
    valid_from timestamptz   NOT NULL,
    valid_to   timestamptz,
    price_usd  numeric(12,2) NOT NULL CHECK (price_usd > 0),
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);

-- Many-to-many with attributes: who can supply each product, at what cost.
CREATE TABLE product_suppliers (
    product_id     bigint        NOT NULL,
    supplier_id    bigint        NOT NULL,
    unit_cost_usd  numeric(12,2) NOT NULL,
    lead_time_days integer       NOT NULL,
    is_primary     boolean       NOT NULL
);

CREATE TABLE inventory (
    warehouse_id     bigint      NOT NULL,
    product_id       bigint      NOT NULL,
    quantity_on_hand integer     NOT NULL CHECK (quantity_on_hand >= 0),
    reorder_point    integer     NOT NULL,
    updated_at       timestamptz NOT NULL
);

CREATE TABLE promotions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    code         text         NOT NULL,
    name         text         NOT NULL,
    discount_pct numeric(5,2) NOT NULL CHECK (discount_pct > 0 AND discount_pct < 100),
    starts_at    timestamptz  NOT NULL,
    ends_at      timestamptz  NOT NULL,
    CHECK (ends_at > starts_at)
);

CREATE TABLE promotion_products (
    promotion_id bigint NOT NULL,
    product_id   bigint NOT NULL
);

-- ---------------------------------------------------------------------------
-- Shopping and orders
-- ---------------------------------------------------------------------------

CREATE TABLE carts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint      NOT NULL,
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE cart_items (
    cart_id    bigint      NOT NULL,
    product_id bigint      NOT NULL,
    quantity   integer     NOT NULL CHECK (quantity > 0),
    added_at   timestamptz NOT NULL DEFAULT now()
);

-- Money columns are in the ORDER currency (currency_code). To report in USD
-- you must convert with the fx rate that was valid when the order was placed.
CREATE TABLE orders (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id         bigint        NOT NULL,
    shipping_address_id bigint        NOT NULL,
    promotion_id        bigint,
    status              text          NOT NULL CHECK (status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled')),
    currency_code       char(3)       NOT NULL,
    subtotal            numeric(14,2) NOT NULL,
    discount            numeric(14,2) NOT NULL,
    shipping_fee        numeric(14,2) NOT NULL,
    tax                 numeric(14,2) NOT NULL,
    total               numeric(14,2) NOT NULL,
    placed_at           timestamptz   NOT NULL,
    updated_at          timestamptz   NOT NULL,
    CHECK (total = subtotal - discount + shipping_fee + tax)
);

-- Composite primary key (order_id, line_no), like SalesOrderDetail.
CREATE TABLE order_items (
    order_id   bigint        NOT NULL,
    line_no    smallint      NOT NULL,
    product_id bigint        NOT NULL,
    quantity   integer       NOT NULL CHECK (quantity > 0),
    unit_price numeric(12,2) NOT NULL,           -- order currency, before discount
    discount   numeric(12,2) NOT NULL DEFAULT 0  -- total discount for the line
);

CREATE TABLE payments (
    id       bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint        NOT NULL,
    method   text          NOT NULL CHECK (method IN ('card', 'paypal', 'bank_transfer', 'gift_card', 'pix')),
    status   text          NOT NULL CHECK (status IN ('authorized', 'captured', 'refunded', 'failed')),
    amount   numeric(14,2) NOT NULL,
    paid_at  timestamptz   NOT NULL
);

CREATE TABLE shipments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id        bigint      NOT NULL,
    warehouse_id    bigint      NOT NULL,
    carrier         text        NOT NULL,
    tracking_number text        NOT NULL,
    status          text        NOT NULL CHECK (status IN ('preparing', 'in_transit', 'delivered')),
    shipped_at      timestamptz NOT NULL,
    delivered_at    timestamptz,
    CHECK (delivered_at IS NULL OR delivered_at >= shipped_at)
);

-- A return points to one order LINE: composite foreign key (order_id, line_no).
CREATE TABLE returns (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id      bigint        NOT NULL,
    line_no       smallint      NOT NULL,
    quantity      integer       NOT NULL CHECK (quantity > 0),
    reason        text          NOT NULL CHECK (reason IN ('damaged', 'wrong_item', 'wrong_size', 'not_as_described', 'changed_mind', 'late_delivery')),
    status        text          NOT NULL CHECK (status IN ('requested', 'approved', 'refunded', 'rejected')),
    refund_amount numeric(12,2) NOT NULL,
    requested_at  timestamptz   NOT NULL
);

CREATE TABLE reviews (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id  bigint      NOT NULL,
    customer_id bigint      NOT NULL,
    rating      smallint    NOT NULL CHECK (rating BETWEEN 1 AND 5),
    title       text        NOT NULL,
    body        text        NOT NULL,
    created_at  timestamptz NOT NULL
);
